### PR TITLE
vtprotobuf: Reuse backing array with referenced structs instead of pooling individual objects

### LINKED ISSUE #20: vtproto UnmarshalVT is allocating since pointer is nil
After #17 , we set pointer elements in slices to nil. This is good for our usage since we needed access to pooled `Keyed*`. I think vtproto has a preference to not pool individual elements, as shown in https://github.com/elastic/apm-aggregation/blob/main/aggregationpb/aggregation_vtproto.pb.go#L2907 . New structs are not obtained from pool, even they have the `*FromVTPool` method. #17 did not cause a regression in allocs because there is another bug in vtproto causing slices not to be pooled (part of the fix in the fork)

Decide on
1. whether to pool individual elements
    - If yes, fix UnmarshalVT codegen. We pool individual elements in vtproto fork post #17 , but then UnmarshalVT do not obtain struct from VT pool, and it still causes some allocs on UnmarshalVT.
    - If no, remove usages in our codec to obtain individual struct from VT pool. Assume that the pooled slice already contain them. Also need another fix in vtproto to pool the slice properly because it is now being thrown away.

### PR DESCRIPTION
**Pull request by carsonip**
Alternative to #37 , but using vtprotobuf fork that reuses backing array including referenced structs, which has an upstream PR. With this, we will no longer be pooling Keyed* individually. Either with this or #37, there will be significantly fewer garbage.

Closes #20

benchstat:
```
goos: linux
goarch: amd64
pkg: github.com/elastic/apm-aggregation/aggregators
cpu: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
                                       │ bench-out/vt-unmarshal-pooling-including-structs-2-before │ bench-out/vt-unmarshal-pooling-including-structs-2-after │
                                       │                          sec/op                           │              sec/op                vs base               │
AggregateCombinedMetrics-16                                                            2.001µ ± 1%                         1.926µ ± 1%   -3.75% (p=0.002 n=6)
AggregateBatchSerial-16                                                                5.227µ ± 1%                         4.489µ ± 5%  -14.11% (p=0.002 n=6)
AggregateBatchParallel-16                                                              5.524µ ± 9%                         5.008µ ± 3%   -9.33% (p=0.002 n=6)
CombinedMetricsEncoding-16                                                            1410.0n ± 3%                         878.5n ± 2%  -37.69% (p=0.002 n=6)
CombinedMetricsToBatch-16                                                              61.90µ ± 1%                         61.41µ ± 2%        ~ (p=0.132 n=6)
EventToCombinedMetrics-16                                                              420.7n ± 2%                         418.4n ± 3%        ~ (p=0.240 n=6)
NDJSONSerial/go-2.0.0.ndjson-16                                                        19.11m ± 3%                         16.84m ± 4%  -11.88% (p=0.002 n=6)
NDJSONSerial/nodejs-3.29.0.ndjson-16                                                  10.980m ± 4%                         9.488m ± 3%  -13.59% (p=0.002 n=6)
NDJSONSerial/python-6.7.2.ndjson-16                                                    27.13m ± 4%                         23.21m ± 3%  -14.45% (p=0.002 n=6)
NDJSONSerial/ruby-4.5.0.ndjson-16                                                      16.14m ± 1%                         13.95m ± 4%  -13.57% (p=0.002 n=6)
NDJSONParallel/go-2.0.0.ndjson-16                                                      19.17m ± 4%                         16.71m ± 7%  -12.85% (p=0.002 n=6)
NDJSONParallel/nodejs-3.29.0.ndjson-16                                                11.005m ± 3%                         9.518m ± 6%  -13.51% (p=0.002 n=6)
NDJSONParallel/python-6.7.2.ndjson-16                                                  27.26m ± 2%                         23.03m ± 3%  -15.54% (p=0.002 n=6)
NDJSONParallel/ruby-4.5.0.ndjson-16                                                    16.25m ± 3%                         13.98m ± 3%  -13.97% (p=0.002 n=6)
geomean                                                                                458.6µ                              399.0µ       -13.01%

                                       │ bench-out/vt-unmarshal-pooling-including-structs-2-before │ bench-out/vt-unmarshal-pooling-including-structs-2-after │
                                       │                           B/op                            │             B/op              vs base                    │
AggregateCombinedMetrics-16                                                        1.416Ki ±  0%                     1.104Ki ± 1%   -22.01% (p=0.002 n=6)
AggregateBatchSerial-16                                                            2.459Ki ±  2%                     1.373Ki ± 3%   -44.17% (p=0.002 n=6)
AggregateBatchParallel-16                                                          2.500Ki ±  3%                     1.370Ki ± 3%   -45.21% (p=0.002 n=6)
CombinedMetricsEncoding-16                                                           855.0 ± 44%                         0.0 ± 0%  -100.00% (p=0.002 n=6)
CombinedMetricsToBatch-16                                                          3.986Ki ±  3%                     3.982Ki ± 0%         ~ (p=0.502 n=6)
EventToCombinedMetrics-16                                                            0.000 ±  0%                       0.000 ± 0%         ~ (p=1.000 n=6) ¹
NDJSONSerial/go-2.0.0.ndjson-16                                                   11.591Mi ±  0%                     9.249Mi ± 1%   -20.21% (p=0.002 n=6)
NDJSONSerial/nodejs-3.29.0.ndjson-16                                               7.007Mi ±  0%                     5.589Mi ± 1%   -20.23% (p=0.002 n=6)
NDJSONSerial/python-6.7.2.ndjson-16                                                19.59Mi ±  1%                     15.32Mi ± 1%   -21.78% (p=0.002 n=6)
NDJSONSerial/ruby-4.5.0.ndjson-16                                                 10.418Mi ±  0%                     8.261Mi ± 0%   -20.71% (p=0.002 n=6)
NDJSONParallel/go-2.0.0.ndjson-16                                                 11.597Mi ±  0%                     9.233Mi ± 1%   -20.38% (p=0.002 n=6)
NDJSONParallel/nodejs-3.29.0.ndjson-16                                             7.011Mi ±  0%                     5.563Mi ± 1%   -20.66% (p=0.002 n=6)
NDJSONParallel/python-6.7.2.ndjson-16                                              19.63Mi ±  1%                     15.32Mi ± 1%   -21.94% (p=0.002 n=6)
NDJSONParallel/ruby-4.5.0.ndjson-16                                               10.424Mi ±  0%                     8.256Mi ± 0%   -20.80% (p=0.002 n=6)
geomean                                                                                          ²                                 ?                      ² ³
¹ all samples are equal
² summaries must be >0 to compute geomean
³ ratios must be >0 to compute geomean

                                       │ bench-out/vt-unmarshal-pooling-including-structs-2-before │ bench-out/vt-unmarshal-pooling-including-structs-2-after │
                                       │                         allocs/op                         │            allocs/op             vs base                 │
AggregateCombinedMetrics-16                                                           21.00 ± 0%                          17.00 ± 0%  -19.05% (p=0.002 n=6)
AggregateBatchSerial-16                                                               26.00 ± 4%                          13.00 ± 8%  -50.00% (p=0.002 n=6)
AggregateBatchParallel-16                                                             26.50 ± 6%                          13.00 ± 8%  -50.94% (p=0.002 n=6)
CombinedMetricsEncoding-16                                                            0.000 ± 0%                          0.000 ± 0%        ~ (p=1.000 n=6) ¹
CombinedMetricsToBatch-16                                                             95.00 ± 0%                          95.00 ± 0%        ~ (p=1.000 n=6) ¹
EventToCombinedMetrics-16                                                             0.000 ± 0%                          0.000 ± 0%        ~ (p=1.000 n=6) ¹
NDJSONSerial/go-2.0.0.ndjson-16                                                      142.1k ± 0%                         114.1k ± 2%  -19.66% (p=0.002 n=6)
NDJSONSerial/nodejs-3.29.0.ndjson-16                                                 79.18k ± 1%                         63.79k ± 1%  -19.43% (p=0.002 n=6)
NDJSONSerial/python-6.7.2.ndjson-16                                                  215.4k ± 1%                         162.7k ± 1%  -24.49% (p=0.002 n=6)
NDJSONSerial/ruby-4.5.0.ndjson-16                                                   124.53k ± 0%                         98.87k ± 0%  -20.61% (p=0.002 n=6)
NDJSONParallel/go-2.0.0.ndjson-16                                                    142.0k ± 0%                         113.9k ± 1%  -19.81% (p=0.002 n=6)
NDJSONParallel/nodejs-3.29.0.ndjson-16                                               79.20k ± 0%                         63.17k ± 1%  -20.24% (p=0.002 n=6)
NDJSONParallel/python-6.7.2.ndjson-16                                                215.4k ± 2%                         163.2k ± 1%  -24.23% (p=0.002 n=6)
NDJSONParallel/ruby-4.5.0.ndjson-16                                                 124.54k ± 1%                         99.09k ± 0%  -20.43% (p=0.002 n=6)
geomean                                                                                          ²                                    -22.21%               ²
¹ all samples are equal
² summaries must be >0 to compute geomean
```

macro benchmark:
```
                           │ github/run82.txt │         github/run83-vt.txt         │
                           │    events/sec    │  events/sec   vs base               │
10000AggregationGroups-512       13.76k ± 35%   15.90k ± 32%        ~ (p=0.132 n=6)
1000Transactions-512             13.72k ± 33%   18.83k ± 28%        ~ (p=0.065 n=6)
AgentAll-512                     9.124k ± 19%   8.998k ± 50%        ~ (p=0.818 n=6)
AgentGo-512                      11.15k ± 22%   12.01k ± 53%        ~ (p=0.310 n=6)
AgentNodeJS-512                  5.777k ± 28%   6.611k ± 29%        ~ (p=0.093 n=6)
AgentPython-512                  6.825k ± 26%   7.422k ± 76%        ~ (p=0.180 n=6)
AgentRuby-512                    7.332k ± 44%   7.387k ± 67%        ~ (p=0.368 n=6)
geomean                          9.193k         10.23k        +11.28%
```

### CODE REVIEW

File: aggregators/codec.go [hunk 1]
```diff
@@ -82,14 +83,14 @@ func (k *CombinedMetricsKey) SizeBinary() int {
...
-		ksm := aggregationpb.KeyedServiceMetricsFromVTPool()
-		ksm.Key = k.ToProto()
-		ksm.Metrics = m.ToProto()
-		pb.ServiceMetrics = append(pb.ServiceMetrics, ksm)
+		pb.ServiceMetrics = pb.ServiceMetrics[:len(pb.ServiceMetrics)+1]
+		if pb.ServiceMetrics[len(pb.ServiceMetrics)-1] == nil {
+			pb.ServiceMetrics[len(pb.ServiceMetrics)-1] = &aggregationpb.KeyedServiceMetrics{}
+		}
+		pb.ServiceMetrics[len(pb.ServiceMetrics)-1].Key = k.ToProto()
+		pb.ServiceMetrics[len(pb.ServiceMetrics)-1].Metrics = m.ToProto()
```
Comment (lahsivjar) [inline aggregators/codec.go:93]: Why do we need to do this? Why not just directly append?

Comment (axw) [reply aggregators/codec.go:93]: IIANM to get the most benefit we should reuse the existing slice elements. So instead of assigning the result of ToProto, we would need to update the target pb type fields from the intermediate type.

I'll have a stab at that while Carson is sleeping.

Comment (axw) [reply aggregators/codec.go:93]: @lahsivjar to answer your question though, the change is to reuse existing space in the slices:
- the Grow call ensures there's capacity (which may be existing/reused space)
- the reslice on line 88 ensures the slice _length_ is extended into the capacity
- then we index that element directly

The change I mentioned above would be a further optimisation to reuse the existing entry, if non-nil, instead of getting a new value from the pool

Comment (lahsivjar) [reply aggregators/codec.go:93]: Ah, got it. I think it might be better to just reslice once and then use the array semantics for a more readable code.

Something like:

```go
	pb.ServiceMetrics = pb.ServiceMetrics[:len(m.Services)]
	var i int
	for k, m := range m.Services {
		if pb.ServiceMetrics[i] == nil {
			pb.ServiceMetrics[i] = &aggregationpb.KeyedServiceMetrics{}
		}
		pb.ServiceMetrics[i].Key = k.ToProto()
		pb.ServiceMetrics[i].Metrics = m.ToProto()
		i++
	}
```

Comment (axw) [reply aggregators/codec.go:93]: > IIANM to get the most benefit we should reuse the existing slice elements. So instead of assigning the result of ToProto, we would need to update the target pb type fields from the intermediate type.

This doesn't work: although the elements are not set to nil, they are reset. Resetting sends the key and value back to their pools.

Comment (lahsivjar) [reply aggregators/codec.go:93]: That should be because `KeyedServiceMetrics` qualifies as a `ShouldPool` method. If we were to make `KeyedServiceMetrics` not pool we will be able to do that.

Comment (lahsivjar) [reply aggregators/codec.go:93]: To do the above we have 2 choices:

1. Remove `KeyedServiceMetrics` explicitly from the list while generation
2. Mark each message that require pool explicitly in the proto definition

`2` can be done by:

```proto
message {
  option (vtproto.mempool) = true;
  ...
}
```

Comment (lahsivjar) [reply aggregators/codec.go:93]: Above being said, I am not sure if it would be a good idea. A few benchmarks should help make the decisions but without those I think just backing the `.Key` and `.Metrics` with pool (i.e. what is done right now) should be okay.

File: tools/go.mod [hunk 2]
```diff
@@ -17,4 +17,4 @@ require (
 	google.golang.org/protobuf v1.28.1 // indirect
 )
 
-replace github.com/planetscale/vtprotobuf => github.com/carsonip/vtprotobuf v0.0.0-20230711135402-2cf3150fde0e
+replace github.com/planetscale/vtprotobuf => github.com/grafana/vtprotobuf v0.0.0-20230722075033-e8044ca07485
```
[the remark this answers is not in the document]
Comment (axw) [reply tools/go.mod:20]: I think using the grafana fork is fine.

File: aggregators/codec.go (hunk 1 above)
Comment (axw) [reply aggregators/codec.go:93]: I'll abandon this for now, I think it's not likely to yield much. Will get back to looking into parallelism.

@carsonip I think it would be good to tidy up the reslicing and indexing, like @lahsivjar suggested in https://github.com/elastic/apm-aggregation/pull/63#discussion_r1281365678. Then we can come back to the rest later, maybe.

**Review by axw — APPROVED** [review]
Would like to see the reslicing/indexing to the end of the slices tidied up, but otherwise LGTM!

File: aggregators/codec.go (hunk 1 above)
Comment (carsonip) [reply aggregators/codec.go:93]: Thanks @lahsivjar  for the good suggestion.

This rather unappealing piece (at this for this occasion) of code came from vtproto and it was written for Unmarshal in this way since it had no certainly for the length of new slice. In our code, we do, and I added a slices.Grow to ensure there was only 1 alloc if `len(newSlice) < cap(reusedSlice)`. With this `slices.Grow` call, we can do what @lahsivjar suggested, to `pb.ServiceMetrics = pb.ServiceMetrics[:len(m.Services)]` once and remove that reslicing and indexing code.

Comment (carsonip) [reply aggregators/codec.go:93]: On a side note, even though `KeyedServiceMetrics` qualifies as a `ShouldPool`, vtproto Marshal / Unmarshal ignores that and does not use the pool. I pooled individual elements in [my fork](https://github.com/carsonip/vtprotobuf/tree/fix-pooling-unmarshal-from-pool), but it seems that not pooling individual elements is faster. The alternative is implemented in #37

File: aggregators/codec.go [hunk 3]
```diff
@@ -151,24 +154,22 @@ func (k *serviceInstanceAggregationKey) FromProto(pb *aggregationpb.ServiceInsta
...
 	}
-	if len(m.SpanGroups) > cap(pb.SpanMetrics) {
-		pb.SpanMetrics = make([]*aggregationpb.KeyedSpanMetrics, 0, len(m.SpanGroups))
-	}
+
+	pb.SpanMetrics = slices.Grow(pb.SpanMetrics, len(m.SpanGroups))
 	for _, m := range m.SpanGroups {
 		pb.SpanMetrics = append(pb.SpanMetrics, m)
 	}
+
```
Comment (carsonip) [inline aggregators/codec.go:172]: I'm studying this piece of code here and trying to understand why we don't CloneVT here and what happens to the builder when all of this is returned to the VTPool. Will we be sharing memory between VTPool and the metric builder on reuse?

Comment (carsonip) [reply aggregators/codec.go:172]: ToProto only works on structures obtained from VT Unmarshal
